@host = http://localhost:8000

GET {{host}}/api/codeblocks
Accept: application/json

###

GET {{host}}/api/codeblocks/random
Accept: application/json

###

GET {{host}}/api/codeblocks/3
Accept: application/json

###

POST {{host}}/api/codeblocks
Content-Type: application/json

{
  "theCode": "console.log('foo');",
  "title": "Another Block",
  "languageCode": "js"
}

###

PUT {{host}}/api/codeblocks/4
Content-Type: application/json

{
  "id": 4,
  "theCode": "console.log('foo');",
  "title": "A simple block",
  "languageCode": "js"
}

###

DELETE {{host}}/api/codeblocks/4

